<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<div class="container">
    <table class="table table-striped">
        <thead>
        <th>Machine</th>
        <th>Log time</th>
        </thead>
        <tbody>
        <?php
        /**
         * @var MachineResource $listMachine
         */
        foreach ($listMachine as $machine) : ?>
            <tr>
                <td>
                    <a href="<?= add_query_arg(
                        ['machine' => $machine->getName()], menu_page_url('blife-statistical', false)
                    ) ?>"><?= $machine->getName() ?>
                    </a>
                </td>
                <td><?= $machine->getLastTimeUsage() ?></td>
            </tr>
            </a>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
</body>
</html>
